### ISSUE TITLE
Add new book request funcationality to admin side

### ISSUE THREAD

**Issue by Shru95** [Prasad108/BDM_Client#16]
Admin can submit the request for new book, and the data is added to new-book-request table

**Comment by Shru95** [comment]
Hi,
This funcationality is adde.
Commit URL (Client): https://github.com/Prasad108/BDM_Client/commit/7abd1c304a9c22337e054c4f0e308cbf5533eae4

Commit URL (Server): https://github.com/Prasad108/BDM_Server/commit/4463d922653b9ad08bb6066c838cbc01900e8cc4
Regards,
Shruti

**Comment by Prasad108** [comment]
- HI @Shru95  can u please add the functionality to show a user message, whether form was submitted successfully or not.
  - on successful submission u can show toaster successful and redirect user to some other page.
  - on error u can show just error  with the help of toaster.

**Comment by Prasad108** [comment]
Hi @Shru95 

- SuperAdmin side looks awesome

some observations 
- if super-admin does not put any comment and submits the form he gets the Technical error 
- There is no option that admin can see his past submitted requests.
- After successful submission of the form for new book request user just stays on the same page, u can redirect him to the page where all his submitted requests are shown.
- u can add index to table in super-admin side.
- remove the comments and log statements if not needed now.

its great that u fixed everything within inline form for super-admin

**Comment by Prasad108** [comment]
Hi @Shru95 
- Admin GUI looks superb 
---------
#### few things that can be further improved 
* if super-admin does not put any comment and submits the form he gets the Technical error
- we can have delete request option on the admin side. (it will reduce the number of request shown to the admin side)
- use the permissions for controller whenever necessary like :` @RolesAllowed("ROLE_ADMIN")`
- service code for server can be optimized 
`List<NewBookRequest> requests=new ArrayList<NewBookRequest>();
		requests=requestRepo.getNewBookRequestsByUser(name);
		return requests;
`
can be done in one line like 
`return requestRepo.getNewBookRequestsByUser(name);`

---------
- the scroll feature added to the table is really nice 

regards,
@Prasad108
