### ISSUE TITLE
create and manage user in Admin Module

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/BDM_Client#21]
## create user 
- create new user for the center.
- keep the password same as the contact number of the user.

- show the user list of the center

**Comment by Shru95** [comment]
Hi @Prasad108,

I have reviewed this task. User creation is done good, after creating user able to login with that user
Got some of the following point: 
1. For edit user form u can add back button also.
2. While dislaying users list, on mobile tab the button get cropped.PFA.
![button_cropped](https://user-images.githubusercontent.com/46367232/52469936-d89f4380-2bb2-11e9-9e87-046c78c4beb4.png)

Regards,
@Shru95

**Comment by Prasad108** [comment]
@Shru95 
#### with  regards to your comment for the back button,
- i think this is conman requirement for whole application.

#### Proposed solution from my side 
- use the [Breadcrum ](https://mdbootstrap.com/docs/angular/navigation/breadcrumb/)
  - i'm not sure on how it should be implemented i.e.(should we keep it on the each page or should we have some conman component t)
