### ISSUE TITLE
Add new Book to the Challan

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/BDM_Client#4]
## Goal 
- Create the New Page to add the new book.
- Form contents 
  - Drop down to select the Book name
  - Select the book type
  - Select the book Language 
  - enter the Book rate (by default as per the inventory)
  - Enter the Issued Quantity 
- form validations
  - should show only book name of the books present in the inventory
  - should populate the languages and types only what are present in the inventory.
  - User should not be able to issue the quantity more than what is present in the inventory.
  - should not be able to add the new book which is already present to avoid the redundancy.
  - update the total amount of the challan after successful submission of the new book.

**Comment by Shru95** [comment]
Hi,
Reviewed.
Regards,
Shruti
