### ISSUE TITLE
Add new Challan

### ISSUE THREAD

**Issue by Prasad108** [Prasad108/BDM_Client#8]
##Goal 
- Admin should be able to add the new challan
- Button on the challan should open a new page with form to add new challan.
  - The form should contain the drop down to select Issued_to user.
  - Rest of the other thing like Issued_By, issued date, total, received, should be filled automatically at the back end.
  - show the floater message for Success/ Failure. 
 - After successful submission of the form user should be redirected to the edit challan page.
- If failed stay on the same page with Floater error message.

**Comment by Prasad108** [comment]
Hi, @Shru95 please review and suggest any further changes needed

**Comment by Shru95** [comment]
Hi,
Reviewed.
Regards,
Shruti
